### PR TITLE
Revised Gromit Code

### PR DESCRIPTION
**Pull request by RonakRoy**
I cleaned up some of the code in Gromit and made some logic/semantic revisions. I think this is a direction/format/template that we should take future robot's code in (at least specifically the years that involve mechanisms controlled by an iterative control loop).

### CODE REVIEW

**Comment by Adham-Elarabawy** [comment]
Looks good, I think we should have a talk about properly implemented control loops on such mechanisms though because I am pretty sure that a lot of the controls members don't really fully understand how they work(as simple as they are). This revision is much appreciated.

**Comment by Jugue123** [comment]
I did not have a chance to look through the code in its entirety, but the changes made seem like a good form/template for future code that is written.

**Comment by SentientBacon** [comment]
Here's a fun change: I went ahead and added a `Mechanism` abstract class. Most teams have some framework for mechanisms with basic methods; we've simply made classes for every mechanism. I think having something that provides a uniform means of control threads, disable/enable, and zeroing would be a good idea. There's probably (definitely) other methods that might need to be added, but I made all of the mechanisms in `Gromit` extend that class for a thing of what it might look like.

**Comment by MikaO13** [comment]
Hi Ronak, looking through this code for 2023 code so merging this in, thank you for the control loop examples
Fun fact in case you see this - WPILib created `SubsystemBase`, which is very similar to your `Mechanism`

**Comment by RonakRoy** [comment]
Wow, what a blast from the past—glad this three-year old code could maybe be helpful! The addition of `SubsystemBase` is neat, and kind-of makes sense. When I was around, a lot of the new features that got added to WPILib were "adapted" (i.e. stolen) from good teams, and I was, erm, "heavily inspired" by 254 with the implementation of the `Mechanism` stuff. Awesome to see y'all are working on cool stuff!

**Pull request merged**
